### ISSUE TITLE
TRFR Report: May 2022 - Mines

### ISSUE THREAD

**Issue by LoreRaider** [Castigavi/trle_trfr#1]
Here's the report list with some issues or changes that has to be fixed or can be potentially fixed

Stuff to fix:
- [x] Remove useless ".tr4" file in data folder
- [x] Flying flares on the first floor of the room at the beginning
![bandicam 2022-05-20 20-51-04-732](https://user-images.githubusercontent.com/48493527/169618806-27135e5b-0132-4532-937e-86f1d6994840.jpg)
- [x] Illegal slope
![bandicam 2022-05-20 20-52-43-849](https://user-images.githubusercontent.com/48493527/169618927-39344c62-5db2-49f2-aebe-fd464a146aa7.jpg)

Potential stuff to fix:
- [x] The corners of this wooden structure flickers 
![bandicam 2022-05-19 19-54-31-925](https://user-images.githubusercontent.com/48493527/169618238-8e1fa8a7-fcd2-4fc4-a5d9-7ace25e33a1f.jpg)
- [x] The shatter it's too bright, also the trapdoor embeeds inside the wall
![bandicam 2022-05-19 19-58-58-556](https://user-images.githubusercontent.com/48493527/169618254-6216fb24-15be-48c0-b807-61648899e096.jpg)
- [x] Weird blending (can't remember if it's in this version though)
![bandicam 2022-05-19 20-01-24-779](https://user-images.githubusercontent.com/48493527/169618538-96994049-0858-4245-97ea-2c5fa03f896a.jpg)
- [x] The sarcophagus in general it's too dark
![bandicam 2022-05-20 20-19-55-948](https://user-images.githubusercontent.com/48493527/169618755-19eaf451-b079-4f77-a174-f0cb1c175d5f.jpg)
- [x] Lasersight mesh it's different when picked up and put on the revolver

**Comment by Castigavi** [comment]
Fixed most except:

- Sarcophagus just doesn't want to light up. Won't fix.
- Wooden structures would need too much work. Won't fix.
