### ISSUE TITLE
TRFR Report: 2023 Edition

### ISSUE THREAD

**Issue by LoreRaider** [Castigavi/trle_trfr#2]
### General things:
Possible FLEP patches to enable:
- [x] Prevent camera position freeze
- [ ] Reverb for big rooms (using General preset for the rooms should be totally fine) 
- [ ] Vertex shader patch for darker reflections underwater
Here's the setup to copy in the .fps file in case you want to do it:
>  patchpreset=Vertex shader base,1
>  patchpreset=Vertex shader rule 1,1,-1|-1|2|1|-1|1|127,127,127|-1|0,0,0|2

### Level 1
- [ ] Like I said rats feels very slow during the running animation
- [x] Line here, there's probably a texture inside the triangle
![Screenshot 2023-01-08 12-44-17](https://user-images.githubusercontent.com/48493527/211197940-b0da87cc-f969-4137-b65b-5dea43fc1de6.jpg)
- [x] Weird collision here in the middle, possibly the spider web?
![Screenshot 2023-01-08 12-50-08](https://user-images.githubusercontent.com/48493527/211197970-fcab44b3-9082-42f7-87b8-60a327a39453.jpg)
- [ ] She keeps pushing this block in the air
![Screenshot 2023-01-08 12-54-10](https://user-images.githubusercontent.com/48493527/211198140-3b3dbc07-c201-447b-be85-455b6ae2f569.jpg)
Possible solution:
![image](https://user-images.githubusercontent.com/48493527/211198119-afb22692-e3ed-4ecf-ba3f-ce5b020914b8.png)
- [x] Stuck here
![Screenshot 2023-01-08 13-19-30](https://user-images.githubusercontent.com/48493527/211198148-facd5d9f-d256-41ce-8eb8-0e3d6c2a40bd.jpg)
- [ ] Object disappears
https://user-images.githubusercontent.com/48493527/211198302-0cfd8623-90ba-4590-b79d-eae486535675.mp4
- [ ] Crouch roll skip over this fence
https://user-images.githubusercontent.com/48493527/211198317-297300a4-0896-4ef0-9b3a-f85a4e67e7fa.mp4
- [x] Maybe it's better to disable the spikes or use TR1 ones from the plugin lol
https://user-images.githubusercontent.com/48493527/211198373-e0f4d8ab-1002-4253-9207-8b4b3d349371.mp4

### Level 2
- [x] Missing SetFreeHands command on the pedestal animation (noticeable when you pickup the key and the skeleton next to it wakes up, near the cogs mechanism room)
- [x] You can see a loading camera for a second when you load a savegame
![Screenshot 2023-01-08 13-30-30](https://user-images.githubusercontent.com/48493527/211198384-2462fbbc-328e-4715-bd4e-d5963237cafa.jpg)
- [x] Check the visibility box of these statics, they randomly disappear
![Screenshot 2023-01-08 13-36-18](https://user-images.githubusercontent.com/48493527/211198475-8eb06cb5-1e34-4ebb-a6f8-6d3a74cb07ef.jpg)
![Screenshot 2023-01-08 13-44-32](https://user-images.githubusercontent.com/48493527/211198555-b1e3eaec-7359-4690-baf2-f900f7c284ce.jpg)
- [x] Very bright sunbulb on all the first floor
![Screenshot 2023-01-08 13-38-13](https://user-images.githubusercontent.com/48493527/211198491-71c60950-606e-4ab0-94c7-26415eac8779.jpg)
- [x] Minor illegal slope near the secret area, and another one here
![Screenshot 2023-01-08 13-38-58](https://user-images.githubusercontent.com/48493527/211198524-d325a138-d7b5-42db-97af-d87f13e024b0.jpg)
![Screenshot 2023-01-08 13-50-45](https://user-images.githubusercontent.com/48493527/211198574-a22eb577-5ca8-45b9-96d7-4cb25ab78ccd.jpg)
- [x] Little stretched texture
![Screenshot 2023-01-08 13-39-24](https://user-images.githubusercontent.com/48493527/211198546-6419b243-df29-4382-83d2-602952a90198.jpg)
- [x] Bench floating
![Screenshot 2023-01-08 13-54-03](https://user-images.githubusercontent.com/48493527/211198599-8ac9aaa7-b7f5-4ee8-bd89-df4d9c013468.jpg)

**Comment by Castigavi** [comment]
Fixed most issues mentioned. The rest is won't fix.
